# Generated by Django 4.1.2 on 2022-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('miesiac_urodzenia', models.CharField(choices=[(1, 'styczeń'), (2, 'luty'), (3, 'marzec'), (4, 'kwiecień'), (5, 'maj'), (6, 'czerwiec'), (7, 'lipiec'), (8, 'sierpień'), (9, 'wrzesień'), (10, 'październik'), (11, 'listopad'), (12, 'grudzień')], max_length=1)),
            ],
        ),
    ]
