# Generated by Django 4.1.2 on 2022-11-03 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_druzyna_kraj_alter_osoba_imie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druzyna',
            name='kraj',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]', 'Tylko duże litery')]),
        ),
    ]
